# ---------------------------------------------------------------------------
# Core
# ---------------------------------------------------------------------------
variable "subscription_id" {
  description = "Azure subscription ID."
  type        = string
}

variable "tenant_id" {
  description = "Azure AD tenant ID."
  type        = string
}

variable "location" {
  description = "Azure region for all resources."
  type        = string
  default     = "eastus2"
}

variable "environment" {
  description = "Deployment environment (dev, staging, prod)."
  type        = string
  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "environment must be dev, staging, or prod."
  }
}

variable "resource_token" {
  description = "Deterministic short token embedded in globally-unique resource names. Generated by New-TerraformVarsFile in deploy.ps1; reused across re-runs to keep names stable."
  type        = string
  default     = ""
}

# ---------------------------------------------------------------------------
# Resource names (explicit — set via terraform.tfvars.tpl)
# Naming convention: <caf-abbr>-mbr-<env>-<token>
# ---------------------------------------------------------------------------

variable "resource_group_name" {
  description = "Resource group name."
  type        = string
  default     = "rg-mbr-dev"
}

variable "app_identity_name" {
  description = "App managed identity name (used by Container Apps at runtime)."
  type        = string
  default     = "id-mbr-dev-app"
}

variable "deploy_identity_name" {
  description = "Deploy managed identity name (used by GitHub Actions CI/CD)."
  type        = string
  default     = "id-mbr-dev-deploy"
}

variable "key_vault_name" {
  description = "Key Vault name (3-24 chars, globally unique)."
  type        = string
  default     = "kv-mbr-dev"
}

variable "app_insights_name" {
  description = "Application Insights name."
  type        = string
  default     = "appi-mbr-dev"
}

variable "log_analytics_workspace_name" {
  description = "Log Analytics workspace name."
  type        = string
  default     = "log-mbr-dev"
}

variable "ai_services_name" {
  description = "AI Services account name (globally unique, used as Foundry account)."
  type        = string
  default     = "ais-mbr-dev"
}

variable "ai_project_name" {
  description = "AI Foundry project name."
  type        = string
  default     = "proj-mbr-dev"
}

variable "container_registry_name" {
  description = "Container Registry name (alphanumeric only, 5-50 chars, globally unique)."
  type        = string
  default     = "crmbr"
}

variable "storage_account_name" {
  description = "Storage account name (alphanumeric lowercase only, 3-24 chars, globally unique)."
  type        = string
  default     = "sambrdev"
}

variable "container_app_env_name" {
  description = "Container App Environment name."
  type        = string
  default     = "cae-mbr-dev"
}

# ---------------------------------------------------------------------------
# Fabric
# ---------------------------------------------------------------------------
variable "fabric_workspace_id" {
  description = "Microsoft Fabric workspace GUID. Set after Lakehouse creation."
  type        = string
  default     = ""
}

variable "fabric_sql_server" {
  description = "Fabric Lakehouse SQL analytics endpoint hostname."
  type        = string
  default     = ""
}

variable "fabric_sql_database" {
  description = "Fabric Lakehouse SQL database name."
  type        = string
  default     = "lh-mbr-trucking"
}

# ---------------------------------------------------------------------------
# AI model capacity
# ---------------------------------------------------------------------------
variable "gpt41_capacity" {
  description = "TPM capacity for the GPT-4.1 deployment (thousands)."
  type        = number
  default     = 150
}

variable "gpt41_mini_capacity" {
  description = "TPM capacity for the GPT-4.1-mini deployment (thousands)."
  type        = number
  default     = 50
}

# ---------------------------------------------------------------------------
# GitHub OIDC
# ---------------------------------------------------------------------------
variable "github_org" {
  description = "GitHub organisation name for OIDC federated credential. Leave empty to skip."
  type        = string
  default     = ""
}

variable "github_repository" {
  description = "GitHub repository name for OIDC federated credential. Leave empty to skip."
  type        = string
  default     = ""
}

# ---------------------------------------------------------------------------
# Tags
# ---------------------------------------------------------------------------
variable "tags" {
  description = "Tags applied to all resources."
  type        = map(string)
  default     = {}
}
